# Generated by Django 4.1.4 on 2022-12-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsportal',
            name='description',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
